# See also: https://docs.github.com/en/actions
name: Functions as a Service
on:
  workflow_dispatch: {}
  workflow_call: {}
  push:
    branches: [ "main" ]
    paths-ignore:  ['**.gif', '**.md', '**.md.j2', '**.mmd', '**.png', '**.svg']
  pull_request:
    branches: [ "main" ]
    paths-ignore:  ['**.gif', '**.md', '**.md.j2', '**.mmd', '**.png', '**.svg']
permissions:
  contents: read
jobs:
  test:
    name: Functions as a Service Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize
        run: make clean init build
      - name: Run FaaS Demo
        run: ./demos/fission.mk
        env:
          COLUMNS: 150